# NOTE: This name appears in GitHub's Checks API and in workflow's status badge.
name: ci-test

# Trigger the workflow when:
on:
  # A push occurs to one of the matched branches.
  push:
    branches:
      - main
      - stable/*
  # Or when a pull request event occurs for a pull request against one of the
  # matched branches.
  pull_request:
    branches:
      - main
      - stable/*

# Cancel in-progress jobs on same branch.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  e2e-ts-web-core:
    # NOTE: This name appears in GitHub's Checks API.
    name: e2e-ts-web-core
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: Install dependencies and build
        working-directory: client-sdk/ts-web
        run: npm i --foreground-scripts

      - name: 'dev-server: Start'
        working-directory: client-sdk/ts-web/core
        run: npm run-script playground &

      - name: 'proxy: Install Envoy'
        # https://github.com/tetratelabs/archive-envoy
        run: |
          curl -sL 'https://github.com/tetratelabs/archive-envoy/releases/download/v1.26.1/envoy-v1.26.1-linux-amd64.tar.xz' | sudo tar -xJC /opt
          sudo ln -s /opt/envoy-v1.26.1-linux-amd64/bin/envoy /usr/local/bin

      - name: 'proxy: Start'
        working-directory: client-sdk/ts-web/core/playground
        run: ./sample-run-envoy.sh &

      - name: 'testnet: Download artifacts'
        working-directory: tests
        run: ./download-artifacts.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 'testnet: Start'
        working-directory: client-sdk/ts-web/core/playground
        run: ./sample-run-network.sh &

      - name: 'testnet: Wait for node socket'
        run: |
          while [ ! -e /tmp/oasis-net-runner-sdk-core/net-runner/network/client-0/internal.sock ]; do
            sleep 1
          done

      - name: Nodejs e2e run
        working-directory: client-sdk/ts-web/core
        run: node test/e2e-nodejs.js
